# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from components.progress_bar import Progress_Bar
from components.origin_label import Origin_Label
from components.destination_label import Destination_Label
from components.origin_path import Origin_Path
from components.destination_path import Destination_Path
from components.origin_button import Origin_Button
from components.destination_button import Destination_Button
from components.title_label import Title_Label
from components.organize_button import Organize_Button
from components.status_label import Status_Label


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(465, 340)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.progress_bar = Progress_Bar(self.centralwidget)

        self.origin_label = Origin_Label(QtWidgets.QLabel(self.centralwidget))
        self.origin_label.set_origin_label_style()

        self.destination_label = Destination_Label(QtWidgets.QLabel(self.centralwidget))
        self.destination_label.set_destination_label_style()


        self.origin_path = Origin_Path(self.centralwidget)
        self.destination_path = Destination_Path(self.centralwidget)

        self.origin_button = Origin_Button(self.centralwidget, self.origin_path)
        self.destination_button = Destination_Button(self.centralwidget, self.destination_path)


        self.title_label = Title_Label(QtWidgets.QLabel(self.centralwidget))
        self.title_label.set_title_label_style()

        self.status_label = Status_Label(self.centralwidget)

        self.organize_button = Organize_Button(
            self.centralwidget, self.origin_path, self.destination_path,
            self.progress_bar, self.status_label
            )

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass
        # _translate = QtCore.QCoreApplication.translate
        # MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # self.origin_label.setText(_translate("MainWindow", "Origem:"))
        # self.destination_label.setText(_translate("MainWindow", "Destino:"))
        # self.origin_button.setText(_translate("MainWindow", "..."))
        # self.destination_button.setText(_translate("MainWindow", "..."))
        # self.title_label.setText(_translate("MainWindow", ""))
        # self.organize_button.setText(_translate("MainWindow", "Organizar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
